# Generated by Django 4.0.4 on 2023-02-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='height',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='width',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
