# Generated by Django 4.0.4 on 2023-02-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_film_height_film_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='frame_background',
        ),
        migrations.RemoveField(
            model_name='film',
            name='height',
        ),
        migrations.RemoveField(
            model_name='film',
            name='width',
        ),
        migrations.AddField(
            model_name='myphotoframe',
            name='height',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='myphotoframe',
            name='width',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
